// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9jOiLiC1otbgNpocwlqKMzBOh7x4RTU',
    appId: '1:638349590608:web:1fe7957569be7e668ed155',
    messagingSenderId: '638349590608',
    projectId: 'gadgetz-eab3b',
    authDomain: 'gadgetz-eab3b.firebaseapp.com',
    storageBucket: 'gadgetz-eab3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Eq4CYO5bF9edJUdodesC-FtnQmbJtVg',
    appId: '1:638349590608:android:eb5193b4555d4e3a8ed155',
    messagingSenderId: '638349590608',
    projectId: 'gadgetz-eab3b',
    storageBucket: 'gadgetz-eab3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bROnn1zfjlB5vbVWBaCDfSaaWuLr6NY',
    appId: '1:638349590608:ios:51ddbd039a9a62708ed155',
    messagingSenderId: '638349590608',
    projectId: 'gadgetz-eab3b',
    storageBucket: 'gadgetz-eab3b.appspot.com',
    iosClientId: '638349590608-a2k7dvers6vd9gcpkudof9vmm6h1eicp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ogaBassey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1bROnn1zfjlB5vbVWBaCDfSaaWuLr6NY',
    appId: '1:638349590608:ios:51ddbd039a9a62708ed155',
    messagingSenderId: '638349590608',
    projectId: 'gadgetz-eab3b',
    storageBucket: 'gadgetz-eab3b.appspot.com',
    iosClientId: '638349590608-a2k7dvers6vd9gcpkudof9vmm6h1eicp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ogaBassey',
  );
}
